// Generated by ReScript, PLEASE EDIT WITH CARE
'use strict';

var CssJs = require("../src/CssJs.js");
var React = require("react");
var ReactDOMRe = require("reason-react/lib/js/src/legacy/ReactDOMRe.js");
var TestDivsRes = require("./TestDivsRes.js");

CssJs.$$global("html, body", [
      CssJs.margin("zero"),
      CssJs.padding("zero")
    ]);

ReactDOMRe.renderToElementWithId(React.createElement(TestDivsRes.make, {}), "app");

/*  Not a pure module */
