// Generated by ReScript, PLEASE EDIT WITH CARE
'use strict';

var CssJs = require("../src/CssJs.js");
var React = require("react");
var Css_Js_Core = require("bs-css/lib/js/src/Css_Js_Core.js");

var arialNarrow = CssJs.fontFace("Arial FontFace Test", [CssJs.localUrl("Arial Narrow")], "normal", {
      NAME: "num",
      VAL: 500
    }, undefined, undefined);

var section = CssJs.style([
      CssJs.selector("& > h1", [
            CssJs.fontFamily({
                  NAME: "custom",
                  VAL: arialNarrow
                }),
            CssJs.fontSize(CssJs.px(32)),
            CssJs.fontWeight({
                  NAME: "num",
                  VAL: 300
                }),
            CssJs.marginTop("zero")
          ]),
      CssJs.position("relative"),
      CssJs.background(CssJs.hex("f5f5f5")),
      CssJs.margin(CssJs.px(20)),
      CssJs.padding(CssJs.px(10)),
      CssJs.boxShadow(Css_Js_Core.Shadow.box(undefined, CssJs.px(1), CssJs.px(5), undefined, undefined, CssJs.rgba(0, 0, 0, {
                    NAME: "num",
                    VAL: 0.3
                  }))),
      CssJs.boxShadows([
            Css_Js_Core.Shadow.box(undefined, CssJs.px(1), CssJs.px(5), undefined, undefined, CssJs.rgba(0, 0, 0, {
                      NAME: "num",
                      VAL: 0.3
                    })),
            Css_Js_Core.Shadow.box(undefined, CssJs.px(1), CssJs.px(10), undefined, true, CssJs.rgba(255, 255, 255, {
                      NAME: "num",
                      VAL: 0.5
                    }))
          ])
    ]);

var rowLayout = CssJs.style([
      CssJs.display("flex"),
      CssJs.flexDirection("row"),
      CssJs.flexWrap("wrap")
    ]);

var Styles = {
  arialNarrow: arialNarrow,
  section: section,
  rowLayout: rowLayout
};

function Section(Props) {
  var name = Props.name;
  var children = Props.children;
  return React.createElement("section", {
              className: section
            }, React.createElement("h1", undefined, name), React.createElement("div", {
                  className: rowLayout
                }, children));
}

var make = Section;

exports.Styles = Styles;
exports.make = make;
/* arialNarrow Not a pure module */
