// Generated by ReScript, PLEASE EDIT WITH CARE
'use strict';

var Css = require("../src/Css.js");
var Curry = require("bs-platform/lib/js/curry.js");
var React = require("react");
var Section = require("./Section.js");
var Css_AtomicTypes = require("bs-css/lib/js/src/Css_AtomicTypes.js");

Curry._1(Css.insertRule, ".raw-css { display:block; background-color: green; width: 50px; height: 50px; }");

function TestDivsRes(Props) {
  return React.createElement("div", {
              className: Curry._1(Css.style, {
                    hd: Css.background(Css.hex("f5f5f5")),
                    tl: /* [] */0
                  })
            }, React.createElement("div", {
                  className: Curry._1(Css.style, {
                        hd: Css.marginLeft(Css.px(20)),
                        tl: {
                          hd: Css.before({
                                hd: Css.contentRule({
                                      NAME: "attr",
                                      VAL: "class"
                                    }),
                                tl: {
                                  hd: Css.border(Css.px(1), Css.solid, Css.black),
                                  tl: /* [] */0
                                }
                              }),
                          tl: /* [] */0
                        }
                      })
                }, "TEST"), React.createElement(Section.make, {
                  name: "content",
                  children: null
                }, React.createElement("div", {
                      className: Curry._1(Css.style, {
                            hd: Css.marginLeft(Css.px(20)),
                            tl: {
                              hd: Css.before({
                                    hd: Css.contentRule(Css_AtomicTypes.Gradient.linearGradient(Css.deg(45), {
                                              hd: [
                                                Css.zero,
                                                Css.red
                                              ],
                                              tl: {
                                                hd: [
                                                  Css.pct(100),
                                                  Css.blue
                                                ],
                                                tl: /* [] */0
                                              }
                                            })),
                                    tl: {
                                      hd: Css.border(Css.px(1), Css.solid, Css.black),
                                      tl: {
                                        hd: Css.display("inlineBlock"),
                                        tl: {
                                          hd: Css.height(Css.px(18)),
                                          tl: {
                                            hd: Css.width(Css.px(18)),
                                            tl: /* [] */0
                                          }
                                        }
                                      }
                                    }
                                  }),
                              tl: /* [] */0
                            }
                          })
                    }, "linear gradient"), React.createElement("div", {
                      className: Curry._1(Css.style, {
                            hd: Css.marginLeft(Css.px(20)),
                            tl: {
                              hd: Css.before({
                                    hd: Css.contentRule({
                                          NAME: "attr",
                                          VAL: "class"
                                        }),
                                    tl: {
                                      hd: Css.border(Css.px(1), Css.solid, Css.black),
                                      tl: /* [] */0
                                    }
                                  }),
                              tl: /* [] */0
                            }
                          })
                    }, "linear gradient2"), React.createElement("div", {
                      className: Curry._1(Css.style, {
                            hd: Css.marginLeft(Css.px(20)),
                            tl: {
                              hd: Css.before({
                                    hd: Css.contentRules({
                                          hd: "openQuote",
                                          tl: {
                                            hd: {
                                              NAME: "text",
                                              VAL: "foo"
                                            },
                                            tl: {
                                              hd: "closeQuote",
                                              tl: /* [] */0
                                            }
                                          }
                                        }),
                                    tl: {
                                      hd: Css.border(Css.px(1), Css.solid, Css.black),
                                      tl: /* [] */0
                                    }
                                  }),
                              tl: /* [] */0
                            }
                          })
                    }, "contents (quotes)")));
}

var make = TestDivsRes;

exports.make = make;
/*  Not a pure module */
